name = "pokedex-worker"
main = "src/index.ts"
compatibility_date = "2023-10-23"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[vars]
TURSO_URL = "libsql://pokedex-db-balbuenac.turso.io"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOiIyMDIzLTEwLTIzVDAwOjQ2OjUwLjI2OTc5OTNaIiwiaWQiOiI5MTY2ZTFjYi03MTNiLTExZWUtOTRhOC1lNmQ5MDFkNTVjNzgifQ.mqSmvFIazfb1sUvCSaoinrwvx9KdJvDFJXz8yashpbxXtTsCiEbPCSEXjdPVod-UltNXdFDyCfBra3C5JS4JCQ"